### ISSUE TITLE
SlideをEditで動かすとエラーになる

### ISSUE THREAD

**Issue by chelone-glabra** [chelone-glabra/sentakki#1]
foreach中に要素消したようなエラーだけど、果たして？

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at osu.Game.Rulesets.Sentakki.Edit.SentakkiSelectionHandler.HandleMovement(MoveSelectionEvent moveEvent)
   at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer.moveCurrentSelection(DragEvent e) in C:\Users\*\Downloads\osu-master\osu-master\osu.Game\Screens\Edit\Compose\Components\BlueprintContainer.cs:line 490
   at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer.OnDrag(DragEvent e) in C:\Users\*\Downloads\osu-master\osu-master\osu.Game\Screens\Edit\Compose\Components\BlueprintContainer.cs:line 214
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)

```

**Comment by chelone-glabra** [comment]
そもそもslideの実装がよくわからんしプレイ画面に出てこない、自分で作ってみたほうが良いかも

**Comment by LumpBloom7** [comment]
If possible, could you mention such issues on the main PR for the editor, it'll be more visible for me and will allow me to perform fixes on my end. 

可能であれば、エディターのメインPRでそのような問題について言及していただければ、それは私にとってより目立つようになり、私の側で修正を実行できるようになります。 - thx Google translate

**Comment by LumpBloom7** [comment]
This also happen on all note types and not just slides

**Comment by chelone-glabra** [comment]
> If possible, could you mention such issues on the main PR for the editor, it'll be more visible for me and will allow me to perform fixes on my end.
> 
> 可能であれば、エディターのメインPRでそのような問題について言及していただければ、それは私にとってより目立つようになり、私の側で修正を実行できるようになります。 - thx Google translate

Sure! (but im new to github. sorry if could not PR)
and, I had to modify some files of osu!lazer to access the Editor. You do that, too?

もちろんです！(Githubはほぼ初めて使うので、うまくできなかったらごめんなさい)
また、Editorにアクセスするのにosu!lazerのコードを変更しなければなりませんでした。Bloomさんもそのようにしていますか？

**Comment by LumpBloom7** [comment]
The editor is currently unusable outside of the test interface. The test interface is easily accessible by starting the test project and should look like this.

エディターは現在、テストインターフェイスの外部では使用できません。 テストインターフェイスは、テストプロジェクトを開始することで簡単にアクセスでき、次のようになります。

![image](https://user-images.githubusercontent.com/12001167/104121848-bc2d5800-5341-11eb-8ac4-62437a4b4972.png)


(I'm not good at japanese, so the translation may be wrong :P)

**Comment by chelone-glabra** [comment]
I got this screen first, but I didn't know how to use it and ignored it. XD
(im new to osu!lazer too)

Thank you for helping me :)

教えてくれてありがとうございます。

**Comment by LumpBloom7** [comment]
Come join us in the discord channel, it's easier to discuss stuff there. :)

**Comment by chelone-glabra** [comment]
> Come join us in the discord channel, it's easier to discuss stuff there. :)

ah I already joined that :) but did not speak. (cuz english is not first lang :X)

Can I post this Issue to your Repo Issue? Sure! I said, but there is no guarantee that it can be fixed.

**Comment by LumpBloom7** [comment]
> ah I already joined that :) but did not speak. (cuz english is not first lang :X)

No worries, we don't really mind

> Can I post this Issue to your Repo Issue? Sure! I said, but there is no guarantee that it can be fixed.

Don't worry, I'm currently looking into it as well :)
